[package]
name = "lnmp-sdk-rust"
version = "0.5.7"
edition = "2021"
publish = false

[lib]
name = "lnmp_sdk_rust"
path = "src/lib.rs"

[dependencies]
lnmp-core = { workspace = true }
lnmp-embedding = { workspace = true }
