[package]
name = "lnmp-sdk-rust"
version = "0.5.4"
edition = "2021"
publish = false

[lib]
name = "lnmp_sdk_rust"
path = "src/lib.rs"

[dependencies]
lnmp-core = { version = "0.5.4", path = "../../crates/lnmp-core" }
lnmp-embedding = { version = "0.5.4", path = "../../crates/lnmp-embedding" }
