[package]
name = "lnmp-sdk-rust"
version = "0.5.2"
edition = "2021"
publish = false

[lib]
name = "lnmp_sdk_rust"
path = "src/lib.rs"

[dependencies]
lnmp-core = { path = "../../crates/lnmp-core" }
lnmp-embedding = { path = "../../crates/lnmp-embedding" }
